# Generated by Django 5.1 on 2024-08-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
